; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DWIFI_STA_SSID=\"CIT\"
  -DWIFI_STA_PASS=\"teamcit2024\"
  -DWIFI_AP_SSID=\"esp32-salus\"
  -DWIFI_AP_PASS=\"teamcit2024\"
  -DOTA_HOSTNAME=\"esp32-salus\"
  -DOTA_PASSWORD=\"ota1234\"
  -DWIFI_STA_CONNECT_TIMEOUT_MS=10000
  -DCAMERA_TELEMETRY_SERVER_ENABLED=0
  -DCAMERA_TELEMETRY_PORT=80
  -DCAMERA_TELEMETRY_TASK_PERIOD_MS=5
lib_deps =
  bmellink/IBusBM@^1.1.4

[env:esp32dev-ota-sta]
extends = env:esp32dev
upload_protocol = espota
upload_port = esp32-salus.local
upload_flags =
  --auth=ota1234
  --port=3232

[env:esp32dev-ota-ap]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags =
  --auth=ota1234
  --port=3232

[env:esp32dev-raspi-hotspot]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DWIFI_STA_SSID=\"hotspotagv\"
  -DWIFI_STA_PASS=\"hotspotagv123\"
  -DWIFI_AP_SSID=\"esp32-salus\"
  -DWIFI_AP_PASS=\"teamcit2024\"
  -DOTA_HOSTNAME=\"esp32-salus\"
  -DOTA_PASSWORD=\"ota1234\"
  -DWIFI_STA_CONNECT_TIMEOUT_MS=10000
  -DWIFI_STA_STATIC_IP=\"10.42.0.100\"
  -DWIFI_STA_GATEWAY=\"10.42.0.1\"
  -DWIFI_STA_SUBNET=\"255.255.255.0\"
  -DCAMERA_TELEMETRY_SERVER_ENABLED=1
  -DCAMERA_TELEMETRY_PORT=80
  -DCAMERA_TELEMETRY_TASK_PERIOD_MS=5
lib_deps =
  bmellink/IBusBM@^1.1.4

[env:esp32dev-ota-raspi-hotspot]
extends = env:esp32dev-raspi-hotspot
upload_protocol = espota
upload_port = esp32-salus.local
upload_flags =
  --auth=ota1234
  --port=3232

[env:esp32dev-ota-sta-to-raspi-hotspot]
extends = env:esp32dev-raspi-hotspot
upload_protocol = espota
upload_port = esp32-salus.local
upload_flags =
  --auth=ota1234
  --port=3232

[env:esp32dev-ota-ap-to-raspi-hotspot]
extends = env:esp32dev-raspi-hotspot
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags =
  --auth=ota1234
  --port=3232

[env:esp32dev-ota-raspi-hotspot-to-sta]
extends = env:esp32dev
upload_protocol = espota
upload_port = esp32-salus.local
upload_flags =
  --auth=ota1234
  --port=3232
